CREATE TABLE CarListings (
    UUID VARCHAR(255) NOT NULL,
    WEBSITE VARCHAR(255) NOT NULL,
    IMAGE_URL VARCHAR(255),
    YEAR INT NOT NULL,
    MAKE VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2),
    PRIMARY KEY (WEBSITE, MAKE, MODEL, YEAR)
);

--DELETE FROM CarListings;